# Generated by Django 6.0 on 2026-01-07 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('current_weight_kg', models.FloatField(blank=True, null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('sedentary', 'Little/no exercise'), ('light', 'Light exercise'), ('moderate', 'Moderate exercise (3-5 days/wk)'), ('active', 'Very active (6-7 days/wk)'), ('very_active', 'Extra active (very active & physical job)')], max_length=50)),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('maintain', 'Maintain Weight'), ('weight_gain', 'Weight Gain')], default='maintain', max_length=20)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('avoid_beef', models.BooleanField(default=False)),
                ('avoid_pork', models.BooleanField(default=False)),
                ('has_diabetes', models.BooleanField(default=False)),
                ('has_hypertension', models.BooleanField(default=False)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
